language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: python sample_addresses.csv
branches:
  only:
    - master
sudo: false
secure: "jIjC2+xUqeeHixf3tZcXR3+Qie+kLzbNiCUe3VuYwPYWHLY+CQuYPJWlEtRCBIYO2OO2cPzdHtDUAnz39NDMOqZ/zOoDuhehdyDmiEy/DdoDUVOzerIsytK9LTfZWhpOtjqx94YsUeNZsLGF23wNL8RswmI36t8sujrGJ7RzPrBt/f/SbgRScos4HBKos5pptTWyJ8WZiHNzyA0TM8rfbEIOiF2mZbscADSuOKU/7/DHDMN0IDwjEw98BfaSaQnksbLC/YyjIWEX0LB/MuN9TZI8iDxJ4e7OSvWvOb18KdW1FyhynilasQJQclVsdyd8FiETwiwBB52fH2ZK0xEf4wzWJc17h4asYc/9+CMHEWxWcRT2UQOLPSeIShGhdlk6IE1VXo35xUU7maeYBmVSIdxNBrQfVjRDgEeHiMztzwTwECv5yrYhFednEl9z7GbWtKh7NzEDsDVNyQMg2cQ09SOdykx2uoTF9C6ozBb44XICwyuNcy2AbStw96Hfmu5eYwWWOFJAPbez4osWFKtz/zWRSuD94Cy+2MZ5izVurpLOlQvTScdkPg/s8lu293ozq947Di4IYpOMY+ZOrB38mxdSKr9BKIMZ3ykmnn0K8r296hPPrsjFhICnVToWCVOnIWq8voYYhU3WzIhJAbZc1KQxOnaFtHhfHPSWmjJKh1s="
